# Generated by Django 6.1.1 on 2026-09-03 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(choices=[('JO', 'Jordan'), ('SA', 'Saudi Arabia')], db_index=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='catalog_product_price_non_negative'), models.CheckConstraint(condition=models.Q(('location__in', ['JO', 'SA'])), name='catalog_product_location_valid')],
            },
        ),
    ]
