# Generated by Django 6.1.1 on 2026-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('JO', 'Jordan'), ('SA', 'Saudi Arabia')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['location', 'id'], name='catalog_location_id_idx'),
        ),
    ]
